# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0002_auto_20170626_0910'),
        ('envrnmnt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbinstance',
            name='release_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prd.ReleasePart'),
        ),
        migrations.AddField(
            model_name='stlninstance',
            name='release_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prd.ReleasePart'),
        ),
        migrations.AddField(
            model_name='webinstance',
            name='release_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prd.ReleasePart'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
