# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envrnmnt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinstance',
            name='weight',
            field=models.CharField(choices=[('Big', 'For SmartVista project - 30 Gb'), ('Medium', 'For SMSGate, SSO projects - 5 Gb'), ('Small', 'For other project - less 1 Gb')], max_length=200, verbose_name='Weight'),
        ),
    ]
