# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acm', '0002_auto_20170519_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(verbose_name='product_name')),
                ('title', models.CharField(max_length=200, verbose_name='Product title')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Description')),
                ('wiki_url', models.URLField(verbose_name='Wiki/Confluence URL')),
                ('jira', models.CharField(max_length=20, verbose_name='Jira project code')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Is internal')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acm.Institution')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
