# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreleasepart',
            name='work_branch',
        ),
        migrations.RemoveField(
            model_name='releasepart',
            name='work_branch',
        ),
    ]
