# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('can_issue_hotfix', 'Can issue hotfix'), ('can_issue_build', 'Can issue new build'), ('can_issue_release', 'Can issue new release'))},
        ),
    ]
