# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0002_auto_20170608_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-created']},
        ),
    ]
