# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prd', '0002_auto_20170519_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Build number')),
                ('jira', models.CharField(max_length=20, verbose_name='Jira subtask for build')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('released', models.BooleanField(default=False, verbose_name='Is released')),
                ('date_released', models.DateField(verbose_name='Build date')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='HotFix number')),
                ('jira', models.CharField(max_length=20, verbose_name='Jira task for hotfix')),
                ('date_released', models.DateField(verbose_name='HotFix date')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prd.Build')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Release number')),
                ('jira', models.CharField(max_length=20, verbose_name='Jira task for release')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('released', models.BooleanField(default=False, verbose_name='Is released')),
                ('date_released', models.DateField(verbose_name='Release date')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='release',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prd.Product'),
        ),
        migrations.AddField(
            model_name='build',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prd.Release'),
        ),
    ]
