# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0002_auto_20170620_1427'),
        ('prd', '0002_auto_20170627_1817'),
    ]

    operations = [
    ]
