# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0003_auto_20170519_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='jira',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jira task for release'),
        ),
    ]
