# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0003_auto_20170717_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbuild',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalhotfix',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalrelease',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalreleasepart',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
