# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0003_auto_20170613_1814'),
        ('prd', '0003_auto_20170613_1603'),
    ]

    operations = [
    ]
