# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0003_auto_20170613_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='date_released',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Build date'),
        ),
        migrations.AlterField(
            model_name='historicalbuild',
            name='date_released',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Build date'),
        ),
    ]
