# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0004_auto_20170614_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbuild',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalhotfix',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalrelease',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalreleasepart',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhotfix',
            name='date_released',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='HotFix date'),
        ),
        migrations.AlterField(
            model_name='hotfix',
            name='date_released',
            field=models.DateTimeField(auto_now_add=True, verbose_name='HotFix date'),
        ),
    ]
