# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0005_auto_20170618_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotFixRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(blank=True, max_length=40, null=True, verbose_name='Git revision')),
            ],
        ),
        migrations.AlterField(
            model_name='historicalhotfix',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='historicalhotfix',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='hotfix',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='hotfix',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='hotfixrevision',
            name='hotfix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prd.HotFix'),
        ),
        migrations.AddField(
            model_name='hotfixrevision',
            name='release_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prd.ReleasePart'),
        ),
    ]
