# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0006_auto_20170523_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='jira',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jira subtask for build'),
        ),
    ]
