# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0006_merge_20170720_1245'),
        ('prd', '0006_merge_20170720_1107'),
    ]

    operations = [
    ]
