# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0008_auto_20170524_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
