# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acm', '0003_auto_20170525_1545'),
        ('prd', '0010_auto_20170525_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBuild',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Build number')),
                ('jira', models.CharField(blank=True, max_length=20, null=True, verbose_name='Jira subtask for build')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('released', models.BooleanField(default=False, verbose_name='Is released')),
                ('date_released', models.DateField(blank=True, null=True, verbose_name='Build date')),
                ('created', models.DateField(blank=True, editable=False, verbose_name='Created')),
                ('updated', models.DateField(blank=True, editable=False, verbose_name='Updated')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prd.Release')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical build',
            },
        ),
        migrations.CreateModel(
            name='HistoricalHotFix',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='HotFix number')),
                ('jira', models.CharField(blank=True, max_length=20, null=True, verbose_name='Jira task for hotfix')),
                ('date_released', models.DateField(verbose_name='HotFix date')),
                ('created', models.DateField(blank=True, editable=False, verbose_name='Created')),
                ('updated', models.DateField(blank=True, editable=False, verbose_name='Updated')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('build', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prd.Build')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical hot fix',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Product title')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Description')),
                ('wiki_url', models.URLField(blank=True, null=True, verbose_name='Wiki/Confluence URL')),
                ('jira', models.CharField(max_length=20, verbose_name='Jira project code')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Is internal')),
                ('created', models.DateField(blank=True, editable=False)),
                ('updated', models.DateField(blank=True, editable=False)),
                ('specification_repo', models.IntegerField(blank=True, choices=[(517, 'DevOps Team / Autotest carousel'), (470, 'DevOps Team / BackOffice SmartVista2'), (436, 'DevOps Team / Carousel'), (479, 'DevOps Team / Check'), (506, 'DevOps Team / DevOps REST API'), (487, 'DevOps Team / Instances'), (489, 'DevOps Team / Release list module'), (548, 'DevOps Team / RnD GUI'), (514, 'DevOps Team / auth'), (485, 'DevOps Team / installer-builder'), (464, 'DevOps Team / installer_gui'), (425, 'RnD / spec'), (559, 'SMSGate / Notification Specifications'), (537, 'SVWeb / FEAdapter'), (424, 'SVWeb / SV Kernel - Single Sign-On'), (457, 'SVWeb / SVWF'), (456, 'SVWeb / SVWF-Bankmed'), (458, 'SVWeb / SVWF-UI'), (454, 'SVWeb / com.bpcbt.iso8583'), (408, 'SVWeb / smsgateway-sv2')], help_text='Gitlab repostitory ID for product specifications', null=True, verbose_name='Specifications repository')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inst', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='acm.Institution')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical product',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRelease',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Release number')),
                ('jira', models.CharField(blank=True, max_length=20, null=True, verbose_name='Jira task for release')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('released', models.BooleanField(default=False, verbose_name='Is released')),
                ('date_released', models.DateField(blank=True, null=True, verbose_name='Release date')),
                ('created', models.DateField(blank=True, editable=False, verbose_name='Created')),
                ('updated', models.DateField(blank=True, editable=False, verbose_name='Updated')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical release',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReleasePart',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Module name')),
                ('gitlab_id', models.IntegerField(blank=True, choices=[(517, 'DevOps Team / Autotest carousel'), (470, 'DevOps Team / BackOffice SmartVista2'), (436, 'DevOps Team / Carousel'), (479, 'DevOps Team / Check'), (506, 'DevOps Team / DevOps REST API'), (487, 'DevOps Team / Instances'), (489, 'DevOps Team / Release list module'), (548, 'DevOps Team / RnD GUI'), (514, 'DevOps Team / auth'), (485, 'DevOps Team / installer-builder'), (464, 'DevOps Team / installer_gui'), (425, 'RnD / spec'), (559, 'SMSGate / Notification Specifications'), (537, 'SVWeb / FEAdapter'), (424, 'SVWeb / SV Kernel - Single Sign-On'), (457, 'SVWeb / SVWF'), (456, 'SVWeb / SVWF-Bankmed'), (458, 'SVWeb / SVWF-UI'), (454, 'SVWeb / com.bpcbt.iso8583'), (408, 'SVWeb / smsgateway-sv2')], null=True, verbose_name='Gitlab project')),
                ('one_module', models.BooleanField(default=True, help_text='Product have only one module(Product=Module)', verbose_name='One module')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical release part',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='specification_repo',
            field=models.IntegerField(blank=True, choices=[(517, 'DevOps Team / Autotest carousel'), (470, 'DevOps Team / BackOffice SmartVista2'), (436, 'DevOps Team / Carousel'), (479, 'DevOps Team / Check'), (506, 'DevOps Team / DevOps REST API'), (487, 'DevOps Team / Instances'), (489, 'DevOps Team / Release list module'), (548, 'DevOps Team / RnD GUI'), (514, 'DevOps Team / auth'), (485, 'DevOps Team / installer-builder'), (464, 'DevOps Team / installer_gui'), (425, 'RnD / spec'), (559, 'SMSGate / Notification Specifications'), (537, 'SVWeb / FEAdapter'), (424, 'SVWeb / SV Kernel - Single Sign-On'), (457, 'SVWeb / SVWF'), (456, 'SVWeb / SVWF-Bankmed'), (458, 'SVWeb / SVWF-UI'), (454, 'SVWeb / com.bpcbt.iso8583'), (408, 'SVWeb / smsgateway-sv2')], help_text='Gitlab repostitory ID for product specifications', null=True, verbose_name='Specifications repository'),
        ),
        migrations.AlterField(
            model_name='releasepart',
            name='gitlab_id',
            field=models.IntegerField(blank=True, choices=[(517, 'DevOps Team / Autotest carousel'), (470, 'DevOps Team / BackOffice SmartVista2'), (436, 'DevOps Team / Carousel'), (479, 'DevOps Team / Check'), (506, 'DevOps Team / DevOps REST API'), (487, 'DevOps Team / Instances'), (489, 'DevOps Team / Release list module'), (548, 'DevOps Team / RnD GUI'), (514, 'DevOps Team / auth'), (485, 'DevOps Team / installer-builder'), (464, 'DevOps Team / installer_gui'), (425, 'RnD / spec'), (559, 'SMSGate / Notification Specifications'), (537, 'SVWeb / FEAdapter'), (424, 'SVWeb / SV Kernel - Single Sign-On'), (457, 'SVWeb / SVWF'), (456, 'SVWeb / SVWF-Bankmed'), (458, 'SVWeb / SVWF-UI'), (454, 'SVWeb / com.bpcbt.iso8583'), (408, 'SVWeb / smsgateway-sv2')], null=True, verbose_name='Gitlab project'),
        ),
        migrations.AddField(
            model_name='historicalreleasepart',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prd.Product'),
        ),
        migrations.AddField(
            model_name='historicalreleasepart',
            name='release',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prd.Release'),
        ),
        migrations.AddField(
            model_name='historicalrelease',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prd.Product'),
        ),
    ]
