# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0012_auto_20170526_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreleasepart',
            name='one_module',
        ),
        migrations.RemoveField(
            model_name='releasepart',
            name='one_module',
        ),
    ]
