# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0018_auto_20170601_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreleasepart',
            name='work_branch',
        ),
        migrations.RemoveField(
            model_name='releasepart',
            name='work_branch',
        ),
        migrations.AlterField(
            model_name='releasepart',
            name='release',
            field=models.ForeignKey(blank=True, help_text='Specific release number. Skip if all releases have one configurations', null=True, on_delete=django.db.models.deletion.CASCADE, to='prd.Release'),
        ),
    ]
