# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0019_auto_20170601_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreleasepart',
            name='work_branch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Work branch'),
        ),
        migrations.AddField(
            model_name='releasepart',
            name='work_branch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Work branch'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='specification_repo',
            field=models.IntegerField(blank=True, choices=[(3414222, 'Evgeny Kryukov / RnD GUI'), (552633, 'Evgeny Kryukov / entourage'), (2151966, 'Evgeny Kryukov / gitlab-issue'), (552597, 'Evgeny Kryukov / tiksi')], help_text='Gitlab repostitory for product specifications', null=True, verbose_name='Specifications repository'),
        ),
        migrations.AlterField(
            model_name='historicalreleasepart',
            name='gitlab_id',
            field=models.IntegerField(blank=True, choices=[(3414222, 'Evgeny Kryukov / RnD GUI'), (552633, 'Evgeny Kryukov / entourage'), (2151966, 'Evgeny Kryukov / gitlab-issue'), (552597, 'Evgeny Kryukov / tiksi')], null=True, verbose_name='Gitlab project'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification_repo',
            field=models.IntegerField(blank=True, choices=[(3414222, 'Evgeny Kryukov / RnD GUI'), (552633, 'Evgeny Kryukov / entourage'), (2151966, 'Evgeny Kryukov / gitlab-issue'), (552597, 'Evgeny Kryukov / tiksi')], help_text='Gitlab repostitory for product specifications', null=True, verbose_name='Specifications repository'),
        ),
        migrations.AlterField(
            model_name='releasepart',
            name='gitlab_id',
            field=models.IntegerField(blank=True, choices=[(3414222, 'Evgeny Kryukov / RnD GUI'), (552633, 'Evgeny Kryukov / entourage'), (2151966, 'Evgeny Kryukov / gitlab-issue'), (552597, 'Evgeny Kryukov / tiksi')], null=True, verbose_name='Gitlab project'),
        ),
        migrations.AlterUniqueTogether(
            name='releasepart',
            unique_together=set([('name', 'product')]),
        ),
    ]
