# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0021_auto_20170606_1118'),
        ('prd', '0015_auto_20170529_1259'),
    ]

    operations = [
    ]
