# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('env', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.Environment', verbose_name='Environment')),
            ],
        ),
    ]
