# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 08:53
from __future__ import unicode_literals

import cat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'cat', '0001_initial'), (b'cat', '0002_auto_20170613_1614'), (b'cat', '0003_auto_20170613_1623'), (b'cat', '0004_auto_20170614_1034'), (b'cat', '0005_usagelog_hash'), (b'cat', '0006_auto_20170614_1050'), (b'cat', '0007_auto_20170614_1055')]

    initial = True

    dependencies = [
        ('prd', '0003_auto_20170613_1603'),
        ('envrnmnt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('expire', models.CharField(default=120, max_length=200, verbose_name='Expire time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envrnmnt.Environment', verbose_name='Environment')),
                ('prd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prd.Product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('busy', 'Busy'), ('fail', 'Failed')], default='busy', max_length=200, verbose_name='Statuses')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finish time')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prd.Release', verbose_name='Release')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.TestEnvironment', verbose_name='TestEnvironment')),
                ('task', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task')),
                ('hash', models.CharField(default=cat.models._create_hash, editable=False, max_length=10, unique=True)),
            ],
        ),
    ]
