# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat', '0001_squashed_0007_auto_20170614_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
