# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbinstance',
            name='weight',
            field=models.IntegerField(default=1521, verbose_name='Weight'),
        ),
    ]
