# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0002_auto_20170608_1629'),
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testenvironment',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testenvironment',
            name='prd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prd.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='testenvironment',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('busy', 'Busy'), ('disable', 'Disabled')], default='free', max_length=200, verbose_name='Statuses'),
        ),
    ]
