# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testenvironment',
            options={'ordering': ['name'], 'permissions': (('can_unlock', 'Can force unlock stand'), ('can_run', 'Can manual run stand'))},
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('busy', 'Busy'), ('fail', 'Failed'), ('abort', 'Aborted'), ('timeout', 'Timeout')], default='busy', max_length=200, verbose_name='Statuses'),
        ),
    ]
