# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0002_auto_20170626_0910'),
        ('cat', '0002_auto_20170622_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.IntegerField(verbose_name='Count used')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='Finish time')),
                ('sort', models.IntegerField(verbose_name='Sort')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prd.Release')),
            ],
        ),
    ]
