# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0002_auto_20170608_1629'),
        ('cat', '0002_auto_20170608_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('free', 'Free'), ('busy', 'Busy'), ('disable', 'Disabled')], default='free', max_length=200, verbose_name='Statuses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prd.Product', verbose_name='Release')),
            ],
        ),
        migrations.RemoveField(
            model_name='testenvironment',
            name='status',
        ),
        migrations.AddField(
            model_name='usagelog',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.TestEnvironment', verbose_name='TestEnvironment'),
        ),
    ]
