# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_auto_20170616_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testenvironment',
            name='is_active',
        ),
    ]
