# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_usagelog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelog',
            name='hash',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
