# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_auto_20170628_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testenvironment',
            options={'ordering': ['-is_active', 'name'], 'permissions': (('can_unlock', 'Can force unlock stand'), ('can_run', 'Can manual run stand'))},
        ),
        migrations.AddField(
            model_name='testenvironment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
