# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20170531_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbinstance',
            name='dbname',
        ),
    ]
