# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_releasecarousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecarousel',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sort'),
        ),
        migrations.AlterField(
            model_name='releasecarousel',
            name='used',
            field=models.IntegerField(blank=True, null=True, verbose_name='Count used'),
        ),
    ]
