# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20170613_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagelog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='testenvironment',
            name='expire',
            field=models.CharField(default=120, max_length=200, verbose_name='Expire time'),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='finished_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Finish time'),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Start time'),
            preserve_default=False,
        ),
    ]
