# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20170628_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecarousel',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Priority'),
        ),
    ]
