# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20170615_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelog',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.TestEnvironment', verbose_name='Environment'),
        ),
    ]
