# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_auto_20170613_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='testenvironment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
