# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_auto_20170626_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasecarousel',
            options={'ordering': ['sort']},
        ),
        migrations.AlterField(
            model_name='releasecarousel',
            name='sort',
            field=models.IntegerField(default=10, verbose_name='Sort'),
        ),
    ]
