# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_auto_20170531_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinstance',
            name='weight',
            field=models.CharField(choices=[('Big', 'For SmartVista project'), ('Medium', 'For SMSGate, SSO projects'), ('Small', 'For other project')], max_length=200, verbose_name='Weight'),
        ),
    ]
