# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_testenvironment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelog',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prd.Release', verbose_name='Release'),
        ),
    ]
