# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_auto_20170626_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecarousel',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='releasecarousel',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last used'),
        ),
    ]
