# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_auto_20170531_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='STLNInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200, verbose_name='Host')),
                ('host_login', models.CharField(max_length=200, verbose_name='Server name')),
            ],
        ),
        migrations.CreateModel(
            name='WEBInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200, verbose_name='Host')),
                ('port', models.IntegerField(default=1521, verbose_name='Port')),
                ('target_server', models.CharField(max_length=200, verbose_name='Server name')),
                ('host_login', models.CharField(max_length=200, verbose_name='Server name')),
            ],
        ),
    ]
