# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0007_auto_20170626_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecarousel',
            name='used',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Count used'),
        ),
    ]
