# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0008_auto_20170626_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasecarousel',
            options={'ordering': ['used']},
        ),
        migrations.AlterField(
            model_name='releasecarousel',
            name='used',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Priority'),
        ),
    ]
