# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0008_auto_20170601_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinstance',
            name='host_login',
            field=models.CharField(default='weblogic', max_length=200, verbose_name='Host login'),
        ),
        migrations.AlterField(
            model_name='webinstance',
            name='port',
            field=models.IntegerField(default=7001, verbose_name='Port'),
        ),
    ]
