# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0010_auto_20170626_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasecarousel',
            options={'ordering': ['used', 'last_used_at', 'sort']},
        ),
    ]
