# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0011_auto_20170626_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasecarousel',
            options={'ordering': ['count', 'last_used_at', 'sort']},
        ),
        migrations.RemoveField(
            model_name='releasecarousel',
            name='used',
        ),
        migrations.AddField(
            model_name='releasecarousel',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Count'),
        ),
    ]
