# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cat', '0012_environment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbinstance',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='dbinstance',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='stlninstance',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='stlninstance',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='webinstance',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='webinstance',
            name='object_id',
        ),
        migrations.AddField(
            model_name='environment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='environment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
