# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0013_auto_20170626_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecarousel',
            name='last_used_at',
            field=models.DateTimeField(verbose_name='Last used'),
        ),
    ]
