# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0014_auto_20170626_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasecarousel',
            options={'ordering': ['count', 'last_used_at', 'sort'], 'permissions': (('can_order', 'Manual order priority'),)},
        ),
    ]
