# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0014_auto_20170602_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinstance',
            name='login',
            field=models.CharField(max_length=200, verbose_name='DB Login'),
        ),
        migrations.AlterField(
            model_name='dbinstance',
            name='passwd',
            field=models.CharField(max_length=200, verbose_name='DB Password'),
        ),
    ]
