# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0015_auto_20170606_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stlninstance',
            name='host_login',
        ),
        migrations.RemoveField(
            model_name='webinstance',
            name='host_login',
        ),
        migrations.AddField(
            model_name='stlninstance',
            name='passwd',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stlninstance',
            name='port',
            field=models.IntegerField(default=22, verbose_name='Port'),
        ),
        migrations.AddField(
            model_name='stlninstance',
            name='user',
            field=models.CharField(default='svfe', max_length=200, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='webinstance',
            name='login',
            field=models.CharField(default='weblogic', max_length=200, verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='webinstance',
            name='passwd',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
