# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_filter_id', models.IntegerField(verbose_name='Jira  filter')),
                ('empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JiraReportField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Field order')),
                ('field_name', models.CharField(max_length=200, verbose_name='Field name')),
                ('jira_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpt.JiraFilter')),
            ],
        ),
    ]
