# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpt', '0003_jirafilter_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirafilter',
            name='jql',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='JQL jira query'),
        ),
        migrations.AlterField(
            model_name='jirafilter',
            name='interval',
            field=models.IntegerField(blank=True, choices=[(0, 'Every work day'), (1, 'On Monday'), (2, 'On Friday')], null=True, verbose_name='Interval'),
        ),
    ]
